definitions:
  http.Response:
    properties:
      body:
        type: string
      close:
        type: boolean
      contentLength:
        type: integer
      header:
        type: Header
      proto:
        type: string
      protoMajor:
        type: integer
      protoMinor:
        type: integer
      request:
        type: Request
      status:
        type: string
      statusCode:
        type: integer
      tls:
        type: string
      trailer:
        type: Header
      transferEncoding:
        items:
          type: string
        type: array
      uncompressed:
        type: boolean
    type: object
info:
  contact:
    email: horusec@zup.com.br
    name: Horusec
    url: https://github.com/ZupIT/horusec
  description: Service of Horusec.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Horusec-Messages
paths:
  /api/health:
    get:
      consumes:
      - application/json
      description: Check if Health of service it's OK!
      operationId: health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                content:
                  type: string
              type: object
        "500":
          description: INTERNAL SERVER ERROR
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                content:
                  type: string
              type: object
      tags:
      - Health
swagger: "2.0"
